### ISSUE TITLE
Sniffer converting sand causes crash.

### ISSUE THREAD

**Issue by Seigmannen** [TreeOfSelf/CarpetSkyAdditions-Reborn#12]
Here is the crash report. I will have a look at it as well.

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-12-07 07:36:51
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_5321 cannot be cast to class net.minecraft.class_6885 (net.minecraft.class_5321 and net.minecraft.class_6885 are in unnamed module of loader 'knot' @448ff1a8)
	at knot//net.minecraft.class_8153.mdfafc98$carpetskyadditions$lambda$getLootTable$0$1(class_8153.java:689)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at knot//net.minecraft.class_8153.getLootTable(class_8153.java:697)
	at knot//net.minecraft.class_8153.handler$zkh000$carpetskyadditions$dropIronAndSusify(class_8153.java:736)
	at knot//net.minecraft.class_8153.method_49142(class_8153.java:318)
	at knot//net.minecraft.class_8153.method_5773(class_8153.java:406)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:761)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:501)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:406)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:376)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_8153.mdfafc98$carpetskyadditions$lambda$getLootTable$0$1(class_8153.java:689)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1950)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at knot//net.minecraft.class_8153.getLootTable(class_8153.java:697)
	at knot//net.minecraft.class_8153.handler$zkh000$carpetskyadditions$dropIronAndSusify(class_8153.java:736)
	at knot//net.minecraft.class_8153.method_49142(class_8153.java:318)
	at knot//net.minecraft.class_8153.method_5773(class_8153.java:406)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:761)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:501)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:406)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:sniffer (net.minecraft.class_8153)
	Entity ID: 6
	Entity Name: Sniffer
	Entity's Exact location: -1492.40, 71.00, 2277.16
	Entity's Block location: World: (-1493,71,2277), Section: (at 11,7,5 in -94,4,142; chunk contains blocks -1504,-64,2272 to -1489,319,2287), Region: (-3,4; contains chunks -96,128 to -65,159, blocks -1536,-64,2048 to -1025,319,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:501)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:406)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:376)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1069)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Moltemyhr'/1, l='ServerLevel[Test]', x=-1491.87, y=74.02, z=2281.75]]
	Chunk stats: 3442
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 19240 game time, 6602 day time
	Level name: Test
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 59386 (now: false), thunder time: 74208 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 6
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1734)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1072)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:953)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:713)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:292)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by TreeOfSelf** [comment]
Thank you, I will take a look and get it fixed before the 1.21.4 release

**Comment by TreeOfSelf** [comment]
[Fixed ](https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/commit/a8b76d33edb17eddbecbf59a78e7e831e0379437)
